[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = true

#    [[params.social]]
#        title = "Twitter"
#        icon = "fa-twitter"
#        url = "#"
#    [[params.social]]
#        title = "Facebook"
#        icon = "fa-facebook-f"
#        url = "#"
#    [[params.social]]
#        title = "GitHub"
#        icon = "fa-github"
#        url = "#"
#    [[params.social]]
#        title = "LinkedIn"
#        icon = "fa-linkedin-in"
#        url = "#"
#    [[params.social]]
#        title = "Creative Commons"
#        icon = "fa-creative-commons"
#        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Links naar Health Holland"
        [[params.footer.links.links]]
            title = "Health~Holland"
            url = "https://www.health-holland.com/"
        [[params.footer.links.links]]
            title = "Health~Holland Newsletter"
            url = "https://www.lsh-update.com/mkb"
         [[params.footer.links.links]]
             title = "Health~Holland Programs"
             url = "https://www.health-holland.com/programs"
#        [[params.footer.links.links]]
#            title = "Rutrum accumsan dolor"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Mattis rutrum accumsan"
#            url = "#"
#       [[params.footer.links.links]]
#            title = "Suspendisse varius nibh"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Sed et dapibus mattis"
#            url = "#"
        [[params.footer.links]]
            header = "Downloads"
        [[params.footer.links.links]]
            title = "Calltekst-Innovation-Booster-2025"
            url = "/downloads/HH-OH-Calltekst-Innovation-Booster-2025.docx"
         [[params.footer.links.links]]
             title = "Consortium Agreement - clinical studies"
             url = "/downloads/202501 - Consortium Agreement PPP Projects Template - clinical studies_PPP subsidy.docx"
         [[params.footer.links.links]]
             title = "Consortium Agreement - standard"
             url = "/downloads/202501 - Consortium Agreement PPP Projects Template - standard_PPP subsidy.docx"
         [[params.footer.links.links]]
             title = "Template Letter of Commitment 2025 – EN"
             url = "/downloads/Template Letter of Commitment 2025 – Engels.docx"
         [[params.footer.links.links]]
             title = "Template Letter of Commitment 2025 – NL"
             url = "/downloads/Template Letter of Commitment 2025 – Nederlands.docx"
         [[params.footer.links.links]]
             title = "Insert for article 8 Consortium Agreement"
             url = "/downloads/202501 - Insert for article 8 Consortium Agreement - EN.pdf"
         [[params.footer.links.links]]
             title = "TKI-LSH Standaard Budget Form - 2025"
             url = "/downloads/TKI-LSH Standaard Budget Form - 2025 DEF.xlsx"                 
#        [[params.footer.links.links]]
#            title = "Duis neque nisi sed"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Sed et dapibus quis"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Rutrum amet varius"
#            url = "#"

#         [params.footer.contact_form]
#             enabled = true
#             header = "Contact"
#             action = "mailto:c.kleverlaan@acta.nl"
